# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

# menu:
# - {name: 'Interesting Facts',  url: 'facts'}
# - {name: 'Learning Resources', url: 'resources'}
# - {name: 'Sample Posts',       url: 'sample-posts'}
# - {name: 'Documentation',      url: 'documentation'}
# - {name: 'About',              url: 'about'}
# - {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
# social:
# - {icon: 'bilibili', link:    'https://space.bilibili.com/2107210084'}
# - {icon: 'book', link:   'https://www.xiaohongshu.com/user/profile/61cdf30d0000000021024bc0'}
# - {icon: 'weibo', link:  'https://weibo.com/u/7733197310'}
# - {icon: 'envelope', link:   'mailto:zenzenzengle@gmail.com'}
social:
  - {icon: "fab fa-bilibili", link: "https://space.bilibili.com/2107210084"}
  - {icon: "fas fa-book", link: "https://www.xiaohongshu.com/user/profile/61cdf30d0000000021024bc0"}
  - {icon: "fab fa-weibo", link: "https://weibo.com/u/7733197310"}
  - {icon: "fas fa-envelope", link: "mailto:zenzenzengle@gmail.com"}
  - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: '分享这篇文章^_^'

related_posts: '你可能也喜欢…'

post_date_prefix: '写于'

menu:
  - {name: '技术前沿',  url: 'Technology'}
  - {name: '生活方式', url: 'Lifestyle'}
  - {name: '创意创作', url: 'Creation'}
  - {name: '学习笔记', url: 'Learning'} 
  - {name: '思维模式', url: 'Mindset'}

navigation:
  - title: 技术
    category: Technology
  - title: 生活方式
    category: Lifestyle
  - title: 创作
    category: Creation 
  - title: 学习
    category: Learning
  - title: 思维
    category: Mindset